all: biomassBarOn.png logo.png dedo.png regalo.png cerradura.png cloroplastos.jpg fotosintesis.jpg hormigas2.jpg tsimane2.jpg polynesia.png tonga_barco.jpg hereroNamaPrisoners.jpg africa.png brasil1986.jpg brasil2020.jpg bali-offerings.jpg pachamama.jpg verdadesEmpiricas.png whipala.png madre-chimpance.jpg betweenness-centrality-150-partidas-hist.pdf sidewalk_bubblegum_1997.png Venezuela.png Gerardo.jpeg fotoGeneral.jpg 6-hackaton.jpg papers.csv nota7.jpeg

biomassBarOn.png:
	curl -O  https://raw.githubusercontent.com/glandfried/images/master/biomassBarOn.png

logo.png:
	curl -O  https://raw.githubusercontent.com/glandfried/images/master/logos/pEQb.png -O logo.png

cloroplastos.jpg:
	curl -O  https://raw.githubusercontent.com/glandfried/images/master/cloroplastos.jpg

fotosintesis.jpg:
	curl -O  https://raw.githubusercontent.com/glandfried/images/master/fotosintesis.jpg

hormigas2.jpg:
	curl -O  https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/hormigas2.jpg

tsimane2.jpg:
	curl -O  https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/tsimane2.jpg

polynesia.png:
	curl -O  https://raw.githubusercontent.com/glandfried/images/master/polynesia.png

tonga_barco.jpg:
	curl -O  https://raw.githubusercontent.com/glandfried/images/master/tonga_barco.jpg

regalo.png:
	curl -O  https://raw.githubusercontent.com/glandfried/images/master/regalo.png

dedo.png:
	curl -O  https://raw.githubusercontent.com/glandfried/images/master/dedo.png

cerradura.png:
	curl -O  https://raw.githubusercontent.com/glandfried/images/master/cerradura.png

africa.png:
	curl -O  https://raw.githubusercontent.com/glandfried/images/master/Colonial_Africa_1913_map.svg.png -O africa.png

hereroNamaPrisoners.jpg:
	curl -O  https://raw.githubusercontent.com/glandfried/images/master/hereroNamaPrisoners.jpg

brasil1986.jpg:
	curl -O  https://raw.githubusercontent.com/glandfried/images/master/brasil1986.jpg

brasil2020.jpg:
	curl -O  https://raw.githubusercontent.com/glandfried/images/master/brasil2020.jpg

pachamama.jpg:
	curl -O  https://raw.githubusercontent.com/glandfried/images/master/pachamama.jpg

bali-offerings.jpg:
	curl -O  https://raw.githubusercontent.com/glandfried/images/master/bali-offerings.jpg

verdadesEmpiricas.png:
	curl -O  https://raw.githubusercontent.com/glandfried/images/master/verdadesEmpiricas.png

whipala.png:
	curl -O  https://raw.githubusercontent.com/glandfried/images/master/Qulla_Suyu.svg
	convert -density 1200 -resize 1200x1200 Qulla_Suyu.svg whipala.png
	rm Qulla_Suyu.svg

madre-chimpance.jpg:
	curl -O  https://raw.githubusercontent.com/glandfried/images/master/madre-chimpance.jpg

betweenness-centrality-150-partidas-hist.pdf:
	wget https://github.com/glandfried/cultural-centrality/releases/download/doc.1.0.1/static.zip
	unzip static.zip -d ..

sidewalk_bubblegum_1997.png:
	curl -O  https://raw.githubusercontent.com/glandfried/images/master/sidewalk_bubblegum_1997.png

Venezuela.png:
	curl -O  https://raw.githubusercontent.com/glandfried/images/master/bayes/redes/Argentina.png
	curl -O  https://raw.githubusercontent.com/glandfried/images/master/bayes/redes/Bolivia.png
	curl -O  https://raw.githubusercontent.com/glandfried/images/master/bayes/redes/Brasil.png
	curl -O  https://raw.githubusercontent.com/glandfried/images/master/bayes/redes/Chile.png
	curl -O  https://raw.githubusercontent.com/glandfried/images/master/bayes/redes/Colombia.png
	curl -O  https://raw.githubusercontent.com/glandfried/images/master/bayes/redes/Cuba.png
	curl -O  https://raw.githubusercontent.com/glandfried/images/master/bayes/redes/Mexico.png
	curl -O  https://raw.githubusercontent.com/glandfried/images/master/bayes/redes/Peru.png
	curl -O  https://raw.githubusercontent.com/glandfried/images/master/bayes/redes/Uruguay.png
	curl -O  https://raw.githubusercontent.com/glandfried/images/master/bayes/redes/Venezuela.png

Gerardo.jpeg:
	curl -O https://raw.githubusercontent.com/glandfried/images/master/bayes/congreso2023/Gerardo.jpeg

fotoGeneral.jpg:
	curl -O  https://raw.githubusercontent.com/glandfried/images/master/bayes/congreso2023/fotoGeneral.jpg
	convert fotoGeneral.jpg -crop 7024x348+0+240 fotoGeneral.jpg

6-hackaton.jpg:
	curl -O https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/curso/master/programa/2023.2/1-intro.jpg
	curl -O https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/curso/master/programa/2023.2/2-causa.jpg
	curl -O https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/curso/master/programa/2023.2/3-dato.jpg
	curl -O https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/curso/master/programa/2023.2/4-tiempo.jpg
	curl -O https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/curso/master/programa/2023.2/5-decision.jpg
	curl -O https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/curso/master/programa/2023.2/6-hackaton.jpg

papers.csv:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/congreso/releases/download/comunidad/papers.zip
	unzip papers.zip
	rm papers.zip

nota7.jpeg:
	curl -O https://raw.githubusercontent.com/glandfried/images/master/bayes/congreso2023/nota3.jpeg
	curl -O https://raw.githubusercontent.com/glandfried/images/master/bayes/congreso2023/nota4.jpeg
	curl -O https://raw.githubusercontent.com/glandfried/images/master/bayes/congreso2023/nota5.jpeg
	curl -O https://raw.githubusercontent.com/glandfried/images/master/bayes/congreso2023/nota6.jpeg
	curl -O https://raw.githubusercontent.com/glandfried/images/master/bayes/congreso2023/nota7.jpeg
