all: biomassBarOn.png logo.png dedo.png regalo.png cerradura.png cloroplastos.jpg fotosintesis.jpg hormigas2.jpg tsimane2.jpg polynesia.png tonga_barco.jpg hereroNamaPrisoners.jpg africa.png brasil1986.jpg brasil2020.jpg bali-offerings.jpg pachamama.jpg verdadesEmpiricas.png whipala.png madre-chimpance.jpg betweenness-centrality-150-partidas-hist.pdf sidewalk_bubblegum_1997.png

biomassBarOn.png:
	wget https://raw.githubusercontent.com/glandfried/images/master/biomassBarOn.png

logo.png:
	wget https://raw.githubusercontent.com/glandfried/images/master/logos/pEQb.png -O logo.png

cloroplastos.jpg:
	wget https://raw.githubusercontent.com/glandfried/images/master/cloroplastos.jpg

fotosintesis.jpg:
	wget https://raw.githubusercontent.com/glandfried/images/master/fotosintesis.jpg

hormigas2.jpg:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/hormigas2.jpg

tsimane2.jpg:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/tsimane2.jpg

polynesia.png:
	wget https://raw.githubusercontent.com/glandfried/images/master/polynesia.png

tonga_barco.jpg:
	wget https://raw.githubusercontent.com/glandfried/images/master/tonga_barco.jpg

regalo.png:
	wget https://raw.githubusercontent.com/glandfried/images/master/regalo.png

dedo.png:
	wget https://raw.githubusercontent.com/glandfried/images/master/dedo.png

cerradura.png:
	wget https://raw.githubusercontent.com/glandfried/images/master/cerradura.png

africa.png:
	wget https://raw.githubusercontent.com/glandfried/images/master/Colonial_Africa_1913_map.svg.png -O africa.png

hereroNamaPrisoners.jpg:
	wget https://raw.githubusercontent.com/glandfried/images/master/hereroNamaPrisoners.jpg

brasil1986.jpg:
	wget https://raw.githubusercontent.com/glandfried/images/master/brasil1986.jpg

brasil2020.jpg:
	wget https://raw.githubusercontent.com/glandfried/images/master/brasil2020.jpg

pachamama.jpg:
	wget https://raw.githubusercontent.com/glandfried/images/master/pachamama.jpg

bali-offerings.jpg:
	wget https://raw.githubusercontent.com/glandfried/images/master/bali-offerings.jpg

verdadesEmpiricas.png:
	wget https://raw.githubusercontent.com/glandfried/images/master/verdadesEmpiricas.png

whipala.png:
	wget https://raw.githubusercontent.com/glandfried/images/master/Qulla_Suyu.svg
	convert -density 1200 -resize 1200x1200 Qulla_Suyu.svg whipala.png
	rm Qulla_Suyu.svg

madre-chimpance.jpg:
	wget https://raw.githubusercontent.com/glandfried/images/master/madre-chimpance.jpg

betweenness-centrality-150-partidas-hist.pdf:
	wget https://github.com/glandfried/cultural-centrality/releases/download/doc.1.0.1/static.zip
	unzip static.zip -d ..

sidewalk_bubblegum_1997.png:
	wget https://raw.githubusercontent.com/glandfried/images/master/sidewalk_bubblegum_1997.png
